DROP TABLE IF EXISTS STUDENT;

DROP SEQUENCE IF EXISTS SEQ1;

-- Create sequences for autoincrement fields

CREATE SEQUENCE SEQ1
    START WITH 1
	INCREMENT BY 1
	NO MAXVALUE
	NO MINVALUE
	CACHE 1
;

-- Create tables

CREATE TABLE STUDENT (
  student_id INT DEFAULT SEQ1.NEXTVAL PRIMARY KEY,
  first_name VARCHAR(500) NOT NULL,
  last_name VARCHAR(500) NOT NULL,
  id_number VARCHAR(500) NOT NULL,
  grade VARCHAR(500) NOT NULL
);
